name: Atualizar robots.txt

on:
  schedule:
    - cron: '0 */6 * * *'
  workflow_dispatch:

jobs:
  update-robots:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Gerar robots.txt via Dark Visitors
        run: |
          curl -s -X POST https://api.darkvisitors.com/robots-txts \
            -H "Authorization: Bearer ${{ secrets.DV_TOKEN }}" \
            -H "Content-Type: application/json" \
            -d '{"agent_types":["AI Data Scraper","Undocumented AI Agent"],"disallow":"/"}' \
            > robots.txt

      - name: Commit & push dos updates
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add robots.txt
          git commit -m "Atualiza robots.txt via workflow" || echo "Sem mudanças"
          git push

